### ISSUE TITLE
Web specifications used by HbbTV and not in Web Media API spec

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#19]
I've compared the normative references in the November 28th Web Media API spec with the the Web Specs in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) as updated by HbbTV 2.0.1. 
I've created an issue for each one. These are the following;
- [x] - #10 RFC6265 Cookies
- [x] - #11 CSS Text Module Level 3 
- [x] - #12 CSSOM View Module 
- [x] - #13 DOM level 3 events 
- [x] - #14 Media Fragments URI 
- [x] - #15 Web Messaging 
- [x] - #16 Websocket protocol - RFC6455 
- [x] - #17 Server-sent events 
- [x] - #18 Web audio

I've created an issue for each spec to make it easier to organise the discussion and remember the reasons for whatever we decide in the future.

**Comment by mavgit** [comment]
Suggest we close this issue #19 and continue the discussion in the issues above.

**Comment by jpiesing** [comment]
@mavgit I created this issue to track the subsidiary issues and not to have any discussion here.

**Comment by mavgit** [comment]
We are adding check marks to the list above as referenced sub-issues are closed. We will close this issue when all the sub-issues are closed.

**Comment by davemevans** [comment]
All items in the checklist have been addressed in one way or another. Closing.
