### ISSUE TITLE
 requirements from web video providers beyond presence or absence of an API

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#55]
There are a number of requirements which web video providers have found it necessary to specify which relate to web technologies but which are not simply the presence or absence of a particular API. I've created separate issues for each topic. No discussion is expected here.
- [ ] - #42 - accuracy of reporting the the current playback position for the media element
- [ ] - #43 - requirements on MSE buffering and timing 
- [ ] - #44 - launching first page of web app in full screen mode
- [ ] - #45 - root certificates for TLS
- [ ] - #46 - requirements on number of simultaneous HTTP connections
- [ ] - #47 - requirements on URL length
- [ ] - #48 - requirements on graphics resolution for rendering browser UI
- [ ] - #49 - relationship of graphics resolution and coordinate spaces to video resolution / coordinates
- [ ] - #50 - minimum requirements on devices being able to generate certain key events
- [ ] - #52 - formatting of HTTP user agent string
- [ ] - #53 - Application loading & transition times
- [ ] - #54  - Minimum graphics performance

I've not created issues for two topics that we are already discussing.
- size and persistence of storage for cookies and web storage API
- still image formats

**Comment by mavgit** [comment]
I don't believe that WAVE should be redefining our referenced specs (HTML 5.1, MSE, etc.) when we perceive a lack of clarity or lack of precision or lack of requirements in the currently referenced specs. Instead, I would suggest alternate paths be pursued that improve those specs for all:

1. Check with WAVE app developers to see if this is a problem that is blocking app development.
2. File an issue or question with the appropriate Working Group and/or spec editors on the perceived problem to get their perspective.
3. If we then agree a change is needed, file an issue or bug to get a change made to the appropriate spec.

In no circumstances should WAVE be trying to offer "improvements" to the referenced specs outside of the W3C (or other) spec process, particularly if we haven't attempted to work within the spec process by doing any of the three proposed constructive engagements listed above.

**Comment by jpiesing** [comment]
> I don't believe that WAVE should be redefining our referenced specs (HTML 5.1, MSE, etc.) when we perceive a lack of clarity or lack of precision or lack of requirements in the currently referenced specs. 

I don't believe that is what is proposed. From my understanding, most of the sub-issues below this one address topics which are outside the scope of what is typically addressed in W3C specifications.

**Comment by mavgit** [comment]
I've tentatively marked issues 42-54 with a new "Porting" label to mean we'd move these issues to the porting spec. However, we won't actually move any issues till we have consensus.

**Comment by NevBosak** [comment]
**Size & persistence of cookies and data stored by web storage API**
This decision should be left to the user-agent, to avoid repeats of [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=178980).

**Comment by michelnev** [comment]
Can't remember if there were decisions made on the still image formats, but we'd suggest this:

- shall: PNG, GIF, and JPG
- should: SVG

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#21
